### ISSUE TITLE
V1 Tracking Issue

### ISSUE THREAD

**Issue by broofa** [broofa/flightcard#35]
## Bugs
* [ ] UI chromw for Launch home and other authorized, but not-a-launch pages

## Features 
* [ ] "Verify Attendees" view
* [ ] First pass at launch stats
